### ISSUE TITLE
AttributeError: module 'dateutil' has no attribute 'tz'

### ISSUE THREAD

**Issue by sebma** [dateutil/dateutil#770]
Hi,

I'm working on Ubuntu 17.10, and I'm using `dateutil` v`2.7.3` : 

```python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import dateutil

In [2]: dateutil.__version__
Out[2]: '2.7.3'

In [3]: myTZ = dateutil.tz.tzlocal()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-2eaa368ffa09> in <module>()
----> 1 myTZ = dateutil.tz.tzlocal()

AttributeError: module 'dateutil' has no attribute 'tz'
```
Can you please help me ?

**Comment by sebma** [comment]
But if I do this, it works : 

```python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import dateutil

In [2]: dateutil.tz.tzlocal()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-4e6b7d1dec41> in <module>()
----> 1 dateutil.tz.tzlocal()

AttributeError: module 'dateutil' has no attribute 'tz'

In [3]: from dateutil import tz

In [4]: dateutil.tz.tzlocal()
Out[4]: tzlocal()
```

**Comment by pganssle** [comment]
@sebma Yes. This is because `dateutil` currently is essentially a namespace package for the various sub-modules. The reason for this is that each of the sub-modules should be imported lazily as needed. if you only need `dateutil.tz`, you don't necessarily want to have to import `relativedelta` and `parser` as well.

For a while I've been considering a more seamless lazy-load experience that works as users expect it to. I've created issue #771 to track the implementation.

Until then, use `import dateutil.tz` or `from dateutil import tz` when you want to use `dateutil.tz`.
